---
- hosts: all
  gather_facts: no
  vars_files:
    - vars/main.yml

  roles:
    - role: dhcp
      tags: [ never, dhcp, infra ]
      when: inventory_hostname == "gw"

    - role: dns
      tags: [ never, dns, infra ]
      when: inventory_hostname == "gw"