---
# tasks file for dhcp

- name: Wait 300 seconds, but only start checking after 60 seconds
  wait_for_connection:
    delay: 60
    timeout: 300

- name: Gather facts for first time
  setup:

- name: Install needed network manager libs
  package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - python3-libsemanage
      - python3-policycoreutils
    state: present

- name: Install DHCP
  tags: install
  block:

    - name: Install packages for DHCP
      dnf:
        name:
          - dhcp-server
          - python3-netaddr
          - firewalld
        state: present

    - name: Starting firewalld
      service:
        name: firewalld
        enabled: yes
        state: restarted

    - name: setup firewall
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: "{{ firewall_zone }}"
      with_items: dhcp

    - name: Copy over configuration
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf

    - name: Starting services
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - dhcpd
      register: dhcp_status
      retries: 60
      until: dhcp_status.changed